name: pytest demo

on:
  push:
    branches: 
      - main

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # Choose your desired Python version
          cache: 'pip'  # Cache pip dependencies

      - name: pip inst reqs
        run: pip install -r requirements.txt

      - name: run pytest case
        run: |
          #pytest -v --md-report --md-report-flavor jekyll --md-report-output ./source/index.rst ./testdemo.py
          pytest -v --self-contained-html --html=./source/report_$(date -I).html ./testdemo.py

      - name: Build HTML
        run: |
          sphinx-build -b html ./source ./build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          #enable_jekyll: true