name: pytest demo

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # Choose your desired Python version
          cache: 'pip'  # Cache pip dependencies

      - name: inst req
        run: pip install -r requirements.txt

      - name: run pytest case
        run: |
          pwd
          pytest -v --md-report --md-report-output ./result/report.md ./testdemo.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./result
          publish_branch: main
