name: pytest demo

on:
  workflow_dispatch: 
  push:
    branches: 
      - main

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # Choose your desired Python version
          cache: 'pip'  # Cache pip dependencies

      - name: pip inst reqs
        run: pip install -r requirements.txt

      - name: run pytest case
        run: |
          pytest ./testdemo.py

      - name: Build HTML
        run: |
          cd docs
          sphinx-build -M html source _build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/
          #enable_jekyll: true