name: pytest demo

on:
  workflow_dispatch: 
  push:
    branches: 
      - main

jobs:
  build:
    permissions:
      # for gh-pages
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Set timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Singapore"
          timezoneMacos: "Asia/Singapore"
          timezoneWindows: "Singapore Standard Time"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # Choose your desired Python version
          cache: 'pip'  # Cache pip dependencies

      - name: pip inst reqs
        run: pip install -r requirements.txt

      - name: run pytest case
        run: |
          pytest ./testdemo.py

      - name: Build HTML
        run: |
          cd docs
          sphinx-build -M html source _build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # because i use 'separate' while run sphnix-quickstart
          publish_dir: ./docs/_build/html/
          #enable_jekyll: true